services:
    server:
        restart: always
        container_name: app
        build:
            context: .
        depends_on:
            - mongo
        environment:
            NODE_ENV: production
        expose:
            - 3030
        ports:
            - "3030:3030"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo:4.4
        ports:
            - "27017:27017"
